spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:kafka:29092}
    consumer:
      group-id: community-service-group

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: community-service
    prefer-ip-address: false
